#ifndef __VIDE_PROJECT_DEFINITIONS_H_
#define __VIDE_PROJECT_DEFINITIONS_H_

enum ProjectDefinitionType
{
    DEF_NONE,
    DEF_UNKNOWN,
    DEF_NAMESPACE,
    DEF_CLASS,
    DEF_CLASS_TEMPLATE,
    DEF_FUNCTION_SPEC,
    DEF_FUNCTION_IMPL,
    DEF_FUNCTION_TEMPLATE,
    DEF_FIELD,
    DEF_VARIABLE,
    DEF_ENUM,
    DEF_ENUM_CONSTANT,
    DEF_TYPEDEF,
    DEF_PACKAGE,
};

#endif
