
#include "buildtools/gnu.h"
#include "utils.h"

using namespace std;

VIDE_PLUGIN(GNUBuildTool)

GNUBuildTool::GNUBuildTool(Vide* vide) : MakefileBuildTool(vide)
{
}

GNUBuildTool::~GNUBuildTool()
{
}

FileHandlerPriority GNUBuildTool::canHandle(Project* project)
{
    string confFile = project->getRootPath() + "/configure";
    if (!Utils::fileIsExecutable(confFile))
    {
        // No configure file found
        return PRIORITY_UNSUPPORTED;
    }

    printf("GNUBuildTool::canHandle: Found configure file, checking version...\n");
    string version = Utils::exec(project->getRootPath(), "./configure --version");
printf("GNUBuildTool::canHandle: %s\n", version.c_str());

string::size_type pos = version.find("generated by GNU Autoconf");
printf("GNUBuildTool::canHandle: Is Autoconf=%lu\n", pos);
if (pos == string::npos)
{
    return PRIORITY_UNSUPPORTED;
}

    return PRIORITY_HIGH;
}


